import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Poppins , Inter} from 'next/font/google'
import './globals.css'
const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin']
})
const interFont = Inter({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin']
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${interFont .variable} antialiased`}
      >

        <CartProvider>
          <WishlistProvider>
            <Navbar />
            {children}
            <Footer />
            <ToastContainer />
          </WishlistProvider>
        </CartProvider>

      </body>
    </html>
  );
}
